import Head from "next/head";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.scss";

import Poster from "../components/Poster";
import Project from "../components/Project";
import Project2 from "../components/Project2";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello world</h1>
        <Poster />
        <Project />
        <div className="layoutTest">
          <Project />
        </div>
        <Project2 />
        <div className="layoutTest">
          <Project2 />
        </div>
      </main>
      {/* <Footer /> */}
    </div>
  );
}
