import Head from "next/head";
import Image from "next/image";
import styles from "../styles/LinksPage.module.scss";

const links = [
  {
    platform: "Personal Website",
    url: "/",
    shortUrl: "heydusan.com",
  },
  {
    platform: "Github",
    url: "https://github.com/DEmanderbag",
    shortUrl: "github.com/DEmanderbag",
  },
  {
    platform: "Bookmarks",
    url: "/bookmarks",
    shortUrl: "heydusan.com/bookmarks",
  },
  {
    platform: "Playground",
    url: "/playground",
    shortUrl: "heydusan.com/playground",
  },
  {
    platform: "Twitter",
    url: "https://twitter.com/demanderbag_",
    shortUrl: "twitter.com/demanderbag_",
  },
  {
    platform: "Linkedin",
    url: "https://www.linkedin.com/in/dusan-milosevic/",
    shortUrl: "linkedin.com/in/dusan-milosevic",
  },
];

export default function LinksPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.about}>
          <div className={styles.imageWrapper}>
            <Image
              src="/DusanMilosevic.jpeg"
              alt="Photo of me with glasses with the tree the background"
              width={400}
              height={400}
              layout="responsive"
              priority
            />
          </div>
          <p>
            I&apos;m a Frontend developer working in the medical field and
            currently living in Antwerp Belgium. My development stack is focused
            on performance and accessibility, while using latest technology.
          </p>
        </div>
        <div>
          {links.map((link, index) => (
            <a
              target="_blank"
              rel="noreferrer"
              href={link.url}
              key={link.platform}
            >
              <div className={styles.card}>
                <div className={styles.platform}>
                  <p className={styles.decoration}>
                    {index < 9 ? `0${index + 1}` : index + 1}
                  </p>
                  <div>
                    <p className={styles.title}>{link.platform}</p>
                    <p className={styles.shortUrl}>{link.shortUrl}</p>
                  </div>
                </div>
              </div>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
}
